config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'users#index'
  resources :users, only: [:index, :show] do
   resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
   end
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post

    return unless user.present? # For normal Users

    can :manage, Post, author_id: user.id
    can :manage, Comment, user_id: user.id
    can :create, Like

    return unless user.admin? # For Admins only

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comments_counter
  after_destroy :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_counter
  after_destroy :update_counter

  # Validation: Title must not be blank & Title must not exceed 250 characters.
  validates :title, presence: true, length: { maximum: 250 }

  validates :text, presence: true, length: { maximum: 1000 }

  # Validation: CommentsCounter must be an integer greater than or equal to zero.
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Validation: LikesCounter must be an integer greater than or equal to zero.
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_counter
    user.update(posts_counter: user.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # Validation: Name must not be blank.
  validates :name, presence: true
  # Validation: PostsCounter must be an integer greater than or equal to zero.
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  before_action :set_user, only: %i[index create]
  before_action :set_post, only: %i[index create]

  def index
    @comments = @post.comments
    render json: @comments
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      render json: @comment
    else
      render json: @comment.errors
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = @user.posts.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:index]
  before_action :set_user, only: [:index]

  def index
    @posts = @user.posts
    render json: @posts
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Must be disable for API applications.
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?
  # before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = current_user
    @author = User.find(params[:user_id])
    # Redirection purposes
    @post = Post.find(params[:post_id])
    @comment = @user.comments.build(comment_params)
    if @comment.save
      redirect_to user_post_path(user_id: @author.id, id: @post.id)
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @user = @comment.user
    @author = User.find(params[:user_id])
    return unless @comment.destroy

    redirect_to user_post_path(user_id: @author.id, id: @post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(post_id: @post.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @like = Like.new(user: @user, post: @post)
    return unless @like.save

    redirect_to user_post_path(@user, id: @post.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.build(post_params)
    if @post.save
      redirect_to user_posts_path(@user)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = @post.user
    return unless @post.destroy

    redirect_to user_posts_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<a href="/users/<%= params[:user_id] %>/posts/<%= params[:post_id] %>" class="p-2 px-4 mt-5 text-center text-white bg-red-500 border md:hover:shadow-2xl md:hover:transition md:hover:scale-105">Return</a>
<section class="mt-10">
  <h2 class="text-3xl font-bold md:text-5xl">New Comment</h2>
  <%= form_with model: @comment, url: user_post_comments_path(@user, @post), class: "grid gap-3 mt-10" do |form| %>
    <fieldset class="grid gap-3">
      <%= form.label "Message", class: "text-xl font-bold md:text-2xl" %>
      <%= form.text_area :text, class: "w-full p-2 text-base resize-none border-gray-200 h-40", placeholder: "Message" %>
    </fieldset>
    <fieldset class="flex justify-end">
      <%= form.submit "Create", class: "p-2 px-4 text-center border md:hover:shadow-2xl md:hover:transition md:hover:scale-105 cursor-pointer bg-green-500 font-bold text-white" %>
    </fieldset>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoR | Blog App | John Palacios</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container max-w-screen-xl px-4 mx-auto my-5">
      <%= render 'partials/header' %>

      <div class="mb-5">
        <% if notice %>
        <p class="block p-2 px-4 mt-5 text-center text-white bg-indigo-400 border md:hover:shadow-2xl md:hover:transition"><%= notice %></p>
        <% end %>
        <% if alert %>
        <p class="block p-2 px-4 mt-5 text-center text-white bg-red-400 border md:hover:shadow-2xl md:hover:transition"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_header.html.erb
<header class="mb-5">
  <div class="flex flex-col flex-wrap items-center justify-between gap-3 py-3 mx-auto sm:flex-row">
    <a class="flex items-center font-medium text-gray-900 title-font md:mb-0" href="/">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 p-2 text-white bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-base"> Blog Application  
        <% if user_signed_in?  %>
          | <%= current_user.name %>
        <% end %>
         </span>
    </a>
    <nav class="flex flex-wrap items-center justify-center gap-3 text-base md:ml-auto">
      <a class="text-sm hover:text-gray-900" href="/">Home</a>
      <% if user_signed_in? %>
        <%= form_with(url: destroy_user_session_path, method: :delete, local: false) do |form| %>
          <button type="submit" class="inline-flex items-center px-3 py-1 mt-4 text-base bg-red-300 border-0 rounded focus:outline-none md:hover:bg-gray-200 md:transition md:mt-0">
            Logout
          </button>
        <% end %>
    <% else %>
      <div class="flex items-center gap-3">
        <a class="inline-flex items-center px-3 py-1 text-sm border-0 rounded focus:outline-none md:transition md:mt-0" href="<%= new_user_session_path %>">
        Login
        </a>
        <a class="inline-flex items-center px-3 py-1 text-base bg-indigo-100 border-0 rounded focus:outline-none md:hover:bg-gray-200 md:transition md:mt-0" href="<%= new_user_registration_path %>">
          Sign Up
        </a>
      </div>
    <% end %>
    </nav>
    
  </div>
</header> 

app/views/posts/index.html.erb
<a href="/users/<%= params[:user_id] %>" class="p-2 px-4 mt-5 text-center text-white bg-red-500 border md:hover:shadow-2xl md:hover:transition md:hover:scale-105">Return</a>
<div class="flex flex-col gap-5 mt-10 md:flex-row">
    <picture class="w-40 h-40 mx-auto md:h-40">
      <img src=<%= @user.photo %> alt="" class="object-cover w-full h-full" id="user-photo">
    </picture>
    <div class="flex flex-col justify-between flex-grow p-2 text-center border md:p-6 md:text-left">
      <h3 class="text-3xl font-bold md:text-5xl"><%=  @user.name %></h3>
      <p class="text-xs md:text-right md:text-base md:mt-auto">Number of posts: <%=  @user.posts_counter %></p>
    </div>
</div>
<% if @user == current_user || @user.admin?  %>
  <a href="/users/<%= @user.id %>/posts/new" class="block p-2 px-4 mt-5 text-center text-white bg-blue-600 border md:hover:shadow-2xl md:hover:transition md:hover:scale-105">Create Post</a>
<% end %>
<div class="grid gap-10 mt-10">
  <ul class="grid w-full gap-5 p-0 list-none">
    <% @posts.each do |post| %>
      <li>
        <a class="flex flex-col justify-between flex-grow p-2 text-center border md:text-left md:p-4 md:hover:scale-105 md:transition md:hover:shadow-2xl" href="/users/<%= @user.id %>/posts/<%= post.id %>" id="post-<%= post.title %>">
          <p class="text-xl font-bold md:text-2xl">Post #<%= post.id %> | Title: <%= post.title %></p>
          <p class="mt-3 text-sm md:text-base"><%= post.text %></p>
          <p class="text-xs text-right md:text-base">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
        </a>
      </li>
      <li class="border">
          <ul class="grid w-full p-0 list-none">
            <% post.recent_comments.includes(:user).each do |comment| %>
                <li class="p-2 md:px-4 md:py-1 comment">
                  <p class="text-sm md:text-base"><span class="font-bold"><%= comment.user.name %>:</span> <%= comment.text %></p>
                </li>
            <% end %>
          </ul>
      </li>
    <% end %>
  </ul>
  <section class="flex justify-center" id="pagination">
    <button class="p-2 text-sm transition border rounded-md md:hover:scale-105 md:hover:shadow-2xl">Pagination</button>
  </section>
</div>

app/views/posts/new.html.erb
<a href="/users/<%= params[:user_id] %>/posts" class="p-2 px-4 mt-5 text-center text-white bg-red-500 border md:hover:shadow-2xl md:hover:transition md:hover:scale-105">Return</a>
<section class="mt-10">
  <h2 class="text-3xl font-bold md:text-5xl">New Post</h2>
  <%= form_with model: @post, url: user_posts_path(@user), class: "grid gap-3 mt-10" do |form| %>
    <fieldset class="grid gap-3">
      <%= form.label "Title", class: "text-xl font-bold md:text-2xl" %>
      <%= form.text_field :title, class: "w-full p-2 text-base border-gray-200", placeholder: "Title"  %>
      <%= form.label "Message", class: "text-xl font-bold md:text-2xl" %>
      <%= form.text_area :text, class: "w-full p-2 text-base resize-none border-gray-200 h-40", placeholder: "Message" %>
    </fieldset>
    <fieldset class="flex justify-end">
      <%= form.submit "Create", class: "p-2 px-4 text-center border md:hover:shadow-2xl md:hover:transition md:hover:scale-105 cursor-pointer bg-green-500 font-bold text-white" %>
    </fieldset>
  <% end %>
</section>

app/views/posts/show.html.erb
<a href="/users/<%= params[:user_id] %>/posts" class="p-2 px-4 mt-5 text-center text-white bg-red-500 border md:hover:shadow-2xl md:hover:transition md:hover:scale-105">Return</a>
<section class="grid gap-5 mt-10">
  <article class="p-2 border md:p-4">
    <header class="flex justify-between">
      <h2 class="text-xl font-bold md:text-2xl">Post #<%= @post.id %> | <%= @post.title %> by <%= @user.name %></h2>
      <p class="text-xs md:text-right md:text-base ">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
    </header>
    <div class="text-justify">
      <p class="mt-3 text-sm md:text-base"><%= @post.text %></p>
    </div>
    <div class="flex justify-end gap-3">
      <%= form_with model: @like, url: user_post_likes_path(@user, @post) do |form|%>
      <fieldset>
        <%= form.submit "Add Like", class: "p-2 px-4 text-center border md:hover:shadow-2xl md:hover:transition md:hover:scale-105 cursor-pointer bg-green-500 font-bold text-white" %>
      </fieldset>
    <% end %>
    <% if can? :destroy, @post %>
     <%= button_to 'Delete Post', user_post_path(@user, id: @post.id), :class => 'p-2 px-4 text-center text-white bg-red-500 border md:hover:shadow-2xl md:hover:transition md:hover:scale-105', method: :delete %>
    <% end %>
    </div>
  </article>
  <div class="border">
    <ul class="grid w-full p-0 list-none">
      <% @post.comments.includes(:user).each do |comment| %>
        <li class="flex items-center justify-between p-2 md:px-4 md:py-1">
          <p class="text-sm md:text-base"><span class="font-bold"><%= comment.user.name %>:</span> <%= comment.text %></p>
          <% if can? :destroy, comment %>
            <%= button_to 'Delete Comment', user_post_comment_path(@user, @post, id: comment.id), :class => 'p-1 px-2 text-center text-white bg-red-500 border md:hover:shadow-2xl md:hover:transition md:hover:scale-105 text-sm', method: :delete %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <a href="/users/<%= @user.id %>/posts/<%= @post.id %>/comments/new" class="block p-2 px-4 mt-5 text-center text-white bg-blue-600 border md:hover:shadow-2xl md:hover:transition md:hover:scale-105">Create Comment</a>
</section>

app/views/users/index.html.erb
<h1 class="text-xl font-bold text-center md:text-6xl">List of Users</h1>
<ul class="grid w-full gap-5 p-0 mt-10 list-none">
  <% @users.each do |user| %>
    <li>
      <%= @sum %>
      <a class="flex flex-col gap-5 md:flex-row md:hover:scale-105 md:transition md:hover:shadow-2xl" href="/users/<%= user.id %>">
        <picture class="w-40 h-40 mx-auto md:h-40">
          <img src="<%= user.photo %>" alt="" class="object-cover w-full h-full" id="user-photo">
        </picture>
        <div class="flex flex-col justify-between flex-grow p-2 text-center border md:p-6 md:text-left">
          <h3 class="text-3xl font-bold md:text-5xl"><%= user.name %></h3>
          <p class="text-xs md:text-right md:text-base">Number of posts: <%= user.posts_counter %></p>
        </div>
      </a>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<a href="/users" class="p-2 px-4 mt-5 text-center text-white bg-red-500 border md:hover:shadow-2xl md:hover:transition md:hover:scale-105">Return</a>
<div class="flex flex-col gap-5 mt-10 md:flex-row">
    <picture class="w-40 h-40 mx-auto md:h-40">
      <img src="<%= @user.photo %>" alt="" class="object-cover w-full h-full" id="user-photo">
    </picture>
    <div class="flex flex-col justify-between flex-grow p-2 text-center border md:p-6 md:text-left">
      <h3 class="text-3xl font-bold md:text-5xl"><%=  @user.name %></h3>
      <p class="text-xs md:text-right md:text-base md:mt-auto">Number of posts: <%=  @user.posts_counter %></p>
    </div>
</div>
<div class="p-2 mt-10 border md:p-4">
  <h3 class="text-xl font-bold md:text-2xl">Bio</h3>
  <p class="mt-3 text-sm md:text-base"><%= @user.bio %></p>
</div>
<div class="grid gap-10 mt-10">
  <ul class="grid w-full gap-5 p-0 list-none">
    <% @user.recent_post.each do |post| %>
      <a class="flex flex-col justify-between flex-grow p-2 text-center border md:text-left md:p-4 md:hover:scale-105 md:transition md:hover:shadow-2xl post" href="/users/<%= @user.id %>/posts/<%= post.id %>" id="post-<%= post.title %>">
        <p class="text-xl font-bold md:text-2xl">Post #<%= post.id %></p>
        <p class="mt-3 text-sm md:text-base"><%= post.text %></p>
        <p class="text-xs md:text-right md:text-base ">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
      </a>
    <% end %>
  </ul>
  <div class="flex justify-end">
    <a href="/users/<%= @user.id %>/posts" class="p-2 px-4 text-center text-white bg-blue-600 border md:hover:shadow-2xl md:hover:transition md:hover:scale-105">See all posts</a>
  </div>
</div>